/**
 * @file verifyV2.ts
 * @description Verify all V2 contracts on Etherscan/Basescan
 *
 * Usage:
 *   npx hardhat run scripts/verifyV2.ts --network sepolia
 *   npx hardhat run scripts/verifyV2.ts --network baseSepolia
 *
 * Reads deployment addresses from deployments/{network}-v2.json
 * (generated by deployV2.ts).
 * Skips already-verified contracts.
 */

import { run, network, ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function verifyContract(address: string, constructorArgs: any[], name: string) {
  console.log(`  Verifying ${name} at ${address}...`);
  try {
    await run("verify:verify", {
      address,
      constructorArguments: constructorArgs,
    });
    console.log(`  ✓ ${name} verified`);
  } catch (error: any) {
    if (
      error.message?.includes("Already Verified") ||
      error.message?.includes("already verified")
    ) {
      console.log(`  ✓ ${name} already verified`);
    } else {
      console.log(`  ✗ ${name} failed: ${error.message}`);
    }
  }
}

async function main() {
  const networkName = network.name;
  const outputPath = path.join(__dirname, "..", "deployments", `${networkName}-v2.json`);

  if (!fs.existsSync(outputPath)) {
    throw new Error(`Deployment file not found: ${outputPath}\nRun deployV2.ts first.`);
  }

  const deployment = JSON.parse(fs.readFileSync(outputPath, "utf-8"));
  const c = deployment.contracts;

  console.log(`\nVerifying V2 contracts on ${networkName}...`);

  // ── 1. AdapterRegistry ──────────────────────────────────────────
  // constructor(address _auditGovernance)
  await verifyContract(c.adapterRegistry, [deployment.deployer], "AdapterRegistry");

  // ── 2. MarketDeployer ───────────────────────────────────────────
  // constructor() — no args
  await verifyContract(c.marketDeployer, [], "MarketDeployer");

  // ── 3. MarketFactoryV2 ──────────────────────────────────────────
  // constructor(address _owner, address _protocolTreasury, address _registry, MarketDeployer _marketDeployer)
  await verifyContract(c.marketFactory, [
    deployment.deployer,
    deployment.deployer,
    c.adapterRegistry,
    c.marketDeployer,
  ], "MarketFactoryV2");

  // ── 4. Asset Adapters ───────────────────────────────────────────
  // constructor(address _collateralToken) — deployed with deployer address as placeholder
  await verifyContract(c.erc20Adapter, [deployment.deployer], "ERC20Adapter");
  await verifyContract(c.erc721Adapter, [deployment.deployer], "ERC721Adapter");

  // ── 5. Position Adapters ────────────────────────────────────────
  // constructor(address _factory)
  await verifyContract(c.standardPosition, [c.marketFactory], "StandardPositionAdapter");
  await verifyContract(c.soulboundPosition, [c.marketFactory], "SoulboundPositionAdapter");
  // constructor(address _factory, address _complianceAdapter)
  await verifyContract(c.transferablePosition, [c.marketFactory, ethers.ZeroAddress], "TransferablePositionAdapter");

  // ── 6. Liquidation Adapters ─────────────────────────────────────
  // constructor(address _owner)
  await verifyContract(c.dexSwapLiquidation, [c.marketFactory], "DEXSwapLiquidationAdapter");
  await verifyContract(c.nftAuctionLiquidation, [c.marketFactory], "NFTAuctionLiquidationAdapter");

  console.log("\n✓ Verification complete");
  console.log(`  Deployments file: ${outputPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
