export default {
  overview: 'Overview',
  'design-philosophy': 'Design philosophy',
  'core-contracts': 'Core contracts',
  'adapter-system': 'Adapter system',
  'trust-model': 'Adapter trust model',
  'adapter-registry': 'Adapter registry',
  'validation-matrix': 'Validation matrix',
  'circuit-breaker': 'Circuit breaker',
  'loan-lifecycle': 'Loan lifecycle',
  oracles: 'Oracle adapters',
  liquidations: 'Liquidations',
  positions: 'Position adapters',
  rwa: 'RWA & tokenized equity',
  'lending-assets': 'Lending asset scope',
  'multi-chain': 'Multi-chain',
  compliance: 'Compliance boundary',
  security: 'Security model',
  'data-models': 'Data models',
}
