[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.20"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@chainlink/=node_modules/@chainlink/",
    "@uniswap/=node_modules/@uniswap/",
    "forge-std/=lib/forge-std/src/",
]

[profile.fuzz]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.20"
